### ISSUE TITLE
The website is down, and there isn't documentation anywhere else.

### ISSUE THREAD

**Issue by acnebs** [lume/lume#200]
Title.

**Comment by trusktr** [comment]
Hello Connor, sorry for the late reply! The site is back up.

But I have some news: I've been working on a new website with live code examples, professionally designed, along with a rename of the project. I would love to share that soon!

In the meantime, I'm happy to give any tutorials. Best place to reach me livee is on the Gitter channel: https://gitter.im/infamous/motor (I have Gitter open all the time).

First steps would be to install it (https://infamous.io/docs/install.html), but as far as demos, I don't have much on there.

Once you have things installed, you can run some examples in the `examples/` folder by statically serving them locally.

Let me know if you need any help!

- Joe

**Comment by trusktr** [comment]
This was fixed a while back. :) The new website is: http://lume.io
