### ISSUE TITLE
Components not loading on Opera mobile apps

### ISSUE THREAD

**Issue by skar07** [lume/lume#233]
**On visiting lume.io, through the Opera mobile browser, the components of the website do not seem to load, and only the background is visible.  The actual interactive components, such as the menu and the logo do not load. However, the website seems to load on other browsers, such as Google Chrome.**

Android version:  10
Visible on: Chrome 90.0.4430.210
Not visible on: Opera 63.3.3216.58675

**Steps To Reproduce:**
1. Open Opera browser on the mobile device
2. Visit lume.io

![1622103502046](https://user-images.githubusercontent.com/39200016/119791279-4f7eb880-bef2-11eb-9e01-29b010fa748e.jpg)

**Comment by trusktr** [comment]
@skar07 hello! Thanks for reporting! I think this is fixed now. Does it work for you? This is what I see:

![Uploading Screenshot_20211220-225826.png…]()

**Comment by trusktr** [comment]
Closing, but let's reopen if there's still an issue. Thanks again. :)
