### ISSUE TITLE
Examples are broken

### ISSUE THREAD

**Issue by mootari** [lume/lume#241]
All examples load https://lume.io/docs/global.js which currently returns a 404. This causes `LUME` to be undefined.

**Comment by trusktr** [comment]
Hey, thanks for reporting! The automated deploy goofed for some reason.

**Comment by trusktr** [comment]
Fixed! It took a while because my server broke (it's Arch Linux, a rolling release distro) due to not updating the packages for a long time. I tried to fix it, but it's too far gone. So I migrated the landing and docs sites to 3rd-party deployments.

https://lume.io
