### ISSUE TITLE
Issue with order of plugins in Lume CLI (`lume init`, with all options enabled)

### ISSUE THREAD

**Issue by mrcampbell** [lume/lume#257]
I freaking love Lume, and want to be part of this. 

I was kicking the tires, and so I did the thing any sane human being would do and installed every single plugin. 

I ran into this issue that's a quick fix, but first lemme show you the diagnostics. 

I'd love to do this one myself as I'm trying to get started with small issues.

```bash
➜  lumos deno -V
deno 1.31.1
➜  lumos lume -V
Task lume echo "import 'lume/cli.ts'" | deno run --unstable -A - "-V"
v1.15.3
```

Fresh install as of today.

Here is the issue:

```bash
➜  lumos deno task serve
Task serve deno task lume -s
Task lume echo "import 'lume/cli.ts'" | deno run --unstable -A - "-s"
Loading config file file:///Users/mikecampbell/deno/lumos/_config.ts


Error: PostCSS plugin is required to be installed AFTER TailwindCSS plugin
    at (https://deno.land/x/lume@v1.15.3/plugins/tailwindcss.ts:24:13)
    at Site.use (https://deno.land/x/lume@v1.15.3/core/site.ts:269:5)
    at (file:///Users/mikecampbell/deno/lumos/_config.ts:78:6)
    | 77 | site.use(svgo());
    | 78 | site.use(tailwindcss());
    | ~~ | ~~~~~^
    | 79 | site.use(terser());
```

Just gotta reorder some templates probably. I didn't look into it, but this is a placeholder.

**Comment by mrcampbell** [comment]
They seem to be in alphabetical order, so yeah - I can clean that up!

**Comment by trusktr** [comment]
@mrcampbell hello, I love the enthusiasm! However this repo is a different `lume` project. I think the one you meant to post in is this one: https://github.com/lumeland/lume
