### ISSUE TITLE
Great Lume~ Is it support in Electron app (Windows/macOS)?

### ISSUE THREAD

**Issue by PublicWorld** [lume/lume#274]
Such as above title, thanks.

**Comment by trusktr** [comment]
@PublicWorld Hello, and thanks! Yeah, Lume Elements are just HTML elements written in JavaScript, so they should work in any browser. They work in Chrome, and Electron is just a Chrome browser (with added APIs to access your file system, etc).

If you paste the HTML from this example,

https://docs.lume.io/api/lights/DirectionalLight

into your Electron page, it should just work. Happy to help if any issues.

**Comment by trusktr** [comment]
@PublicWorld closing, but if you have any questions, feel free to ask in Discord or the Forum.
