### ISSUE TITLE
Error in NASA Astrobee Robot example in Android device with destop view enabled.

### ISSUE THREAD

**Issue by vineetjk** [lume/lume#283]
ERROR: Pointercancel should not be happening. If so, please open a bug report. Error: Pointercancel should not be happening. If so, please open a bug report. at r.<anonymous> (https://docs.lume.io/global.js:2:710288)

![Screenshot_20231027-100453_Chrome.jpg](https://github.com/lume/lume/assets/42497152/60195c84-e422-4196-8b05-c4d5070f0ba3)

**Steps to reproduce**

1. Open lume.io in chrome
2. Navigate to examples and select NASA Astrobee Robot
3. Enable desktop view
4. Tap on the rendered 3D scene

**Comment by trusktr** [comment]
Hey, thanks for reporting! That used to work, but pointer event discrepancies between browsers have changed over time and its been a battle. [For](https://github.com/w3c/pointerevents/issues/387) [example](https://bugs.chromium.org/p/chromium/issues/detail?id=1166044).

**Comment by trusktr** [comment]
This was fixed a few days ago. Also the code editor now works very well on mobile! All the demos have a Toggle Fullscreen button now too, making some demos easier to see on mobile.
