### ISSUE TITLE
Some Idea from Adapter & Gadjet

### ISSUE THREAD

**Issue by nitipit** [lume/lume#290]
Hi lume developers,

I took a quick look at lume project and it looks great!
Since it has web components, and you are planning to have CSS & Animation features,
I would like to share some idea from my project
- [Adapter](https://keenlycode.github.io/adapter/) - Adaptive Style Web Component Framework
- [Gadjet](https://github.com/keenlycode/gadjet) - HTML user interface with component based styles -> This UI built on top of **Adapter** Concept

Looking forward to use lume in the future !

**Comment by trusktr** [comment]
Hey, thanks for sharing your projects! Always love to see what people are making with Custom Elements. :) 

If you can make `Adapter` be a mixin function, then later [once Lume has CSS for 3D content](https://github.com/lume/lume/issues/159), `Adapter` could be one way people style the elements (they could apply it to any existing element classes). F.e.:

```js
import {Mesh} from 'lume'
import {Adapter} from '@devcapsule/adapter'

class StyledMesh extends Adapter(Mesh) {}

StyledMesh.classStyle('foo', `
  --material: phong;
  --material-color: skyblue;
  --texture: url(wood.jpg);
  --size-x: 20;
  --size-y: 30;
  --size-z: 40;
  --scale-x: 1;
  --scale-y: 1;
  --scale-z: 1;
  /*etc*/
  transition: --scale-x 1s ease, --scale-y 1s ease, --scale-z 1s ease;
`)
```

Here's how a mixin can be made including the type definition:

https://github.com/lume/lume/blob/c86ca7027e86bc5d774e315adf46308ad5ffb5bf/src/core/ChildTracker.ts#L14

I'll close this as it is not an issue, but feel free keep discussing. Also the forum is great for this type of conversation: https://lume.community (although people have preferred the [Discord](https://discord.gg/PgeyevP) server, but if you do post in the Forums I'll see it and be happy to chat there too)
