### ISSUE TITLE
Does it support pivot?

### ISSUE THREAD

**Issue by WREQI** [lume/lume#291]
Does it support pivot to achieve the effect of babylon.js in the image?
![20190819171516876](https://github.com/lume/lume/assets/35467304/b98efa9d-af2b-42a5-8b4b-78485fc28f98)
![20190819175034437](https://github.com/lume/lume/assets/35467304/d3dd2847-c016-48a6-b996-3d112992f233)

**Comment by trusktr** [comment]
Hello, yeah, it is currently called `origin` in Lume (I wonder if pivot is a better name, so not to confuse with coordinate system origin?).

Docs and example of that are on this page:

https://docs.lume.io/guide/positioning/

**Comment by WREQI** [comment]
![image](https://github.com/lume/lume/assets/35467304/d94291e5-1af5-4635-903f-ac26950a3310)
How to add a transformation controller, where the display center of the controller also follows the set center display?

**Comment by trusktr** [comment]
Not sure I understand what you mean. Do you want to add controls like these?

https://threejs.org/examples/?q=controls#misc_controls_transform

**Comment by trusktr** [comment]
@WREQI Do you still need help? You can add Three.js `TransformControls` to Lume objects. Side note: +Y in Threejs is -Y in Lume. And rotation in Threejs is right-handed while rotation in Lume is left-handed. So if you use Threejs TransformControls and you move along +Y, then you want to negate that when passing it to a Lume `position`.

Closing for now, but please feel free to open a new thread. :)

**Comment by WREQI** [comment]
> 您还需要帮助吗？您可以向 Lume 对象添加Three.js。旁注：Threejs 中的 +Y 是 Lume 中的 -Y。Threejs 中的旋转是右撇子，而 Lume 中的旋转是左撇子。因此，如果您使用 Threejs TransformControls 并沿着 +Y 移动，那么在将其传递给 Lume 时，您需要否定它。`TransformControls``position`
> 
> 暂时关闭，但请随时打开一个新线程。:)
![image](https://github.com/lume/lume/assets/35467304/c4ebb2ee-b5c4-4031-81c9-3234fe4f10c3)

When I modified it with pivot (-0.5,0,0), its bounding box was updated incorrectly, and the center of the TransformControls didn't automatically move to the (-0.5,0,0) position of the pivot

**Comment by WREQI** [comment]
@trusktr
