### ISSUE TITLE
jQuery plugin for calling getters/setters

### ISSUE THREAD

**Issue by trusktr** [lume/lume#8]
So that we can do stuff like

``` js
$('.some-node').rotation([20, 10, 40])
```

if using jQuery.

**Comment by meatflavourdev** [comment]
[http://youmightnotneedjquery.com/](http://youmightnotneedjquery.com/)

**Comment by trusktr** [comment]
@meatflavourdev I totally agree, but there are many sites still using jQuery, that if by the time we roll around to this and there are still sites using jQuery (:rofl:), this could be one way to give more devs the power of LUME. :)

On a more broader note, I've been thinking to make integrations with other more modern libraries and frameworks.

**Comment by trusktr** [comment]
And wow, this issue is 5 years old! I think I'll just close it. jQuery already give people ability to modify element attributes (i.e. they can manipulate LUME elements, which didn't exist at the time I wrote this).  :)

**Comment by meatflavourdev** [comment]
Yup. Let's let jQuery RIP. 🪦🙏🏻🥲
